// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiregen

import (
	"Vox/db"
	"Vox/internal/infrastructure"
)

// Injectors from wire.go:

func InitUserRepositoryImpl() infrastructure.UserRepositoryImpl {
	dbDB := db.NewDBConn()
	userRepositoryImpl := infrastructure.NewUserRepositoryImpl(dbDB)
	return userRepositoryImpl
}
